#if !defined CODE_STORE_BSP_STM3210C_LL_CONFIG_H_
#define CODE_STORE_BSP_STM3210C_LL_CONFIG_H_


///* common */
#define LL_BUS_MODULE_ENABLED
#define LL_CORTEX_MODULE_ENABLED
#define LL_RCC_MODULE_ENABLED
#define LL_SYSTEM_MODULE_ENABLED
#define LL_UTILS_MODULE_ENABLED

///* ALL Peripherals */
#define LL_ADC_MODULE_ENABLED

#define LL_BUS_MODULE_ENABLED

#define LL_CORTEX_MODULE_ENABLED

#define LL_CRC_MODULE_ENABLED

#define LL_DAC_MODULE_ENABLED

#define LL_DMA_MODULE_ENABLED

#define LL_EXTI_MODULE_ENABLED

#define LL_FSMC_MODULE_ENABLED

#define LL_GPIO_MODULE_ENABLED

#define LL_I2C_MODULE_ENABLED

#define LL_IWDG_MODULE_ENABLED

#define LL_PWR_MODULE_ENABLED

#define LL_RCC_MODULE_ENABLED

#define LL_RTC_MODULE_ENABLED

#define LL_SDMMC_MODULE_ENABLED

#define LL_SPI_MODULE_ENABLED

#define LL_SYSTEM_MODULE_ENABLED

#define LL_TIM_MODULE_ENABLED

#define LL_USART_MODULE_ENABLED

#define LL_USB_MODULE_ENABLED

#define LL_UTILS_MODULE_ENABLED

#define LL_WWDG_MODULE_ENABLED



#endif /*CODE_STORE_BSP_STM3210C_LL_CONFIG_H_ */

