#if !defined CODE_STORE_BSP_STM3210C_REDEFINE_IO_H_
#define      CODE_STORE_BSP_STM3210C_REDEFINE_IO_H_

/* LED_GREEN */
#define LED1_GPIO_PORT  GPIOD
#define LED1_GPIO_PIN  LL_GPIO_PIN_7

/* LED_ORANGE */
#define LED2_GPIO_PORT  GPIOD
#define LED2_GPIO_PIN  LL_GPIO_PIN_13

/* LED_RED */
#define LED3_GPIO_PORT  GPIOD
#define LED3_GPIO_PIN  LL_GPIO_PIN_3

/* LED_BLUE */
#define LED4_GPIO_PORT  GPIOD
#define LED4_GPIO_PIN  LL_GPIO_PIN_4


/* BUTTON_KEY */
#define BUTTON1_GPIO_PORT GPIOB
#define BUTTON1_GPIO_PIN  LL_GPIO_PIN_9
#define BUTTON1_GPIO_PULL LL_GPIO_PULL_UP

/* BUTTON_TAMPER */
#define BUTTON2_GPIO_PORT GPIOC
#define BUTTON2_GPIO_PIN  LL_GPIO_PIN_13
#define BUTTON2_GPIO_PULL LL_GPIO_PULL_UP

/* BUTTON_WAKEUP */
#define BUTTON3_GPIO_PORT GPIOA
#define BUTTON3_GPIO_PIN  LL_GPIO_PIN_0
#define BUTTON3_GPIO_PULL LL_GPIO_PULL_DOWN



/**   Software I2C <I2C.c>*/

#define I2C_SW_SCL_GPIO_PORT  GPIOB
#define I2C_SW_SCL_GPIO_PIN   LL_GPIO_PIN_6

#define I2C_SW_SDA_GPIO_PORT  GPIOB
#define I2C_SW_SDA_GPIO_PIN   LL_GPIO_PIN_7

/*
 * I2C1
 */
#define I2C1_SCL_GPIO_PORT	GPIOB
#define I2C1_SCL_GPIO_PIN	LL_GPIO_PIN_6

#define I2C1_SDA_GPIO_PORT	GPIOB
#define I2C1_SDA_GPIO_PIN	LL_GPIO_PIN_7



/* adc											(adc1)*/
#define POTENTION_METER_Clock LL_APB2_GRP1_PERIPH_ADC1
#define POTENTION_METER_Pin LL_GPIO_PIN_4
#define POTENTION_METER_Port GPIOC



//TIM3 Channel1 Output pin
#define TIM3_CHANNEL_1_GPIO_Clock       RCC_APB2ENR_IOPCEN
#define TIM3_CHANNEL_1_Pin 		        LL_GPIO_PIN_6
#define TIM3_CHANNEL_1_Port 		    GPIOC

//TIM3 Channel2 Input pin
#define TIM3_CHANNEL_2_GPIO_Clock       RCC_APB2ENR_IOPAEN
#define TIM3_CHANNEL_2_Pin 		        LL_GPIO_PIN_7
#define TIM3_CHANNEL_2_Port 		    GPIOA

//TIM4 Channel1 input pin
#define TIM4_CHANNEL_1_GPIO_Clock       RCC_APB2ENR_IOPDEN
#define TIM4_CHANNEL_1_Pin 		        LL_GPIO_PIN_12
#define TIM4_CHANNEL_1_Port 		    GPIOD





#endif /* CODE_STORE_BSP_STM3210C_REDEFINE_IO_H_ */
